### PR TITLE
add wtf-16 invariant

### PR DESCRIPTION
**Pull request by codehag**
Discussed in https://github.com/w3ctag/design-principles/issues/323

### CODE REVIEW

**Comment by ljharb** [comment]
I don’t think this is a language invariant - see matchAll - but i also don’t think it’s an invariant at all, it’s a design principle, which is a different thing.

**Comment by codehag** [comment]
This is under **Known Landmines, "shoulds"** not **"Known invariants, "musts"**. I believe that is an appropriate place for it for now.

**Comment by ljharb** [comment]
Ah ok, i didn’t realize there was such a section.

**Comment by codehag** [comment]
my mistake, the section was in fact "precedents" rather than shoulds. I've added text to help clarify.

**Comment by dcodeIO** [comment]
Note that WTF-16 also works on the basis of Unicode code points. The invariant is rather that, like UTF-16, it uses surrogate code points, while in WTF-16 these are not required to come as a pair. As such, what is hidden by the new APIs is the existence of pairs, but the APIs do not hide surrogate code points per-se. Perhaps simplified, one could say that the APIs hide UTF-16 storage details, but not necessarily WTF-16 nature.

(In general, the TAG motion on this topic seems to be target-oriented to me, often skipping over the details up to a point where things don't make sense anymore. LMK if there is interest to improve this.)

**Pull request merged**
